import { FC, ReactElement, useContext } from "react";
import Head from 'next/head'
import AppBar from '@mui/material/AppBar'
import Toolbar from '@mui/material/Toolbar'
import Typography from '@mui/material/Typography'
import Container from '@mui/material/Container'
import Link from 'next/link';
import { Box, Button } from "@mui/material";
import { AuthContext } from "@/provider/AuthProvider";

interface Props {
    children: ReactElement
}
 

const DefaultLayout: FC<Props> = ({ children }) => {
    const { logout, username } = useContext(AuthContext);


    return (  
        <>
            <Head>
                <title>전환 컨테이너</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <AppBar position="sticky" color="primary" component="nav">
                <Toolbar>
                    <Link href="/">
                        <Typography variant="h6">
                        전환 컨테이너
                        </Typography>
                    </Link>
                    <Box sx={{ flexGrow: 1 }}></Box>
                    {
                        username
                        &&
                        <>
                        <Button 
                            color="inherit"
                            onClick={() => {
                            }}    
                        >
                            {username}
                        </Button>
                        <Button 
                            color="inherit"
                            onClick={() => {
                                logout();
                            }}    
                        >
                            로그아웃
                        </Button>
                        </>
                    }
                </Toolbar>
            </AppBar>

            <Container maxWidth="xl">
                <main>
                    { children }
                </main>
            </Container>
        </>
    );
}
 
export default DefaultLayout;