import { FC, ReactElement } from "react";
import Head from 'next/head'
import AppBar from '@mui/material/AppBar'
import Toolbar from '@mui/material/Toolbar'
import Typography from '@mui/material/Typography'
import Container from '@mui/material/Container'
import Link from 'next/link';

interface Props {
    children: ReactElement
}
 

const DefaultLayout: FC<Props> = ({ children }) => {
    return (  
        <>
            <Head>
                <title>전환 컨테이너</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <AppBar position="sticky" color="primary" component="nav">
                <Toolbar>
                    <Link href="/">
                        <Typography variant="h6">
                        전환 컨테이너
                        </Typography>
                    </Link>
                </Toolbar>
            </AppBar>

            <Container maxWidth="xl">
                <main>
                    { children }
                </main>
            </Container>
        </>
    );
}
 
export default DefaultLayout;